USE Collections
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('COLLECTION.item_comment', 'U') IS NOT NULL
BEGIN
	DROP INDEX IF EXISTS U_IDX_coll_attr_id_name ON COLLECTION.item_comment
	DROP TABLE COLLECTION.item_comment
END
GO

CREATE TABLE COLLECTION.item_comment
(
	comment_id		int IDENTITY(1, 1)	NOT NULL ,
	item_id			int					NOT NULL ,
	item_comment	varchar(255)		NOT NULL ,
	create_date		date				NOT NULL DEFAULT GETDATE(),
	create_user		varchar(50)			NOT NULL DEFAULT SYSTEM_USER
)
GO
ALTER TABLE COLLECTION.item_comment ADD PRIMARY KEY NONCLUSTERED 
(
	comment_id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX UC_IDX_itemcomment_commentiditemid ON COLLECTION.item_comment (comment_id, item_id) ON [PRIMARY];
GO

ALTER TABLE COLLECTION.item_comment ADD CONSTRAINT FK_comment_item_id FOREIGN KEY (item_id) REFERENCES COLLECTION.item(item_id)
	ON DELETE CASCADE;
GO
