USE Collections
GO

IF OBJECT_ID('COLLECTION.item', 'U') IS NOT NULL
	DROP TABLE COLLECTION.item
GO

CREATE TABLE COLLECTION.item
(
	item_id			int 			NOT NULL IDENTITY(1, 1) , 
	item_parent		int				NOT NULL ,
	create_date		date			NOT NULL DEFAULT GETDATE(),
	create_user		varchar(255)	NOT NULL DEFAULT SYSTEM_USER
)
GO
ALTER TABLE COLLECTION.item ADD PRIMARY KEY NONCLUSTERED 
(
	item_id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
